apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
